// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy8F-qT1CR66dhuG1hcDAO1S4l8zKGOZM',
    appId: '1:537584520795:android:3384e0ef7224681fe2797e',
    messagingSenderId: '537584520795',
    projectId: 'poptaxi-ae8fd',
    storageBucket: 'poptaxi-ae8fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4tv1kgCEMs2qi0IS5eT8E4LNjveVZQw',
    appId: '1:537584520795:ios:23e0d12463d0b8b6e2797e',
    messagingSenderId: '537584520795',
    projectId: 'poptaxi-ae8fd',
    storageBucket: 'poptaxi-ae8fd.firebasestorage.app',
    iosBundleId: 'com.popdriver.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLEvc5Qo_dolZ1uK8GwTQ1J6dJkKOBh4',
    appId: '1:537584520795:web:6d64971b7337b957e2797e',
    messagingSenderId: '537584520795',
    projectId: 'poptaxi-ae8fd',
    authDomain: 'poptaxi-ae8fd.firebaseapp.com',
    storageBucket: 'poptaxi-ae8fd.firebasestorage.app',
    measurementId: 'G-7508CB7VPX',
  );
}
